baseURL = 'https://toilbusters.com/'
languageCode = 'en-us'
title = 'Toilbusters'
theme = 'binario'
mainSections = ["posts", "projects", "events"]

[params]
disableThemeToggle = true
defaultTheme = "dark"

[params.label]
icon = "logo.png"
iconHeight = "50px"


[[menu.main]]
    name = "Contribute"
    url = "/new-page/"
    weight = 5

[[menu.main]]
    name = "Subscribe"
    url = "/subscribe/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[[menu.main]]
    name = "Latests"
    url = "/new-page/"
    weight = 7
